### ISSUE TITLE
피드백 남깁니다.

### ISSUE THREAD

**Issue by MinKonKim** [Dayeon-Cheon/favorite-countries-typescript#1]
1. styled-component  를 export defualt 이후로 선언해 주셔서, 로직 보기가 편했습니다. 이 점은 
    아주 좋습니다!
2.  props 드릴링을 줄이기 위한 노력이 보입니다. 이 부분은 좋은 거 같네요!

------- CoutryList.tsx 관련  -------

3.  handleToggleCountry 함수에서 , sort를 사용해서 리스트를 정렬해 주는 방법이 인상 깊었습 
     니다. 하지만 만약 countries 의 배열이 길어지면  연산 과정이 느려질 수 있다고 생각 합니다.

4.  "Card"  보단 "CardListWrapper" 혹은 "CardList" 형식으로 변경하면 , 보다 직관적으로 읽힐 
       수 있을 거 같습니다.
------------------------------------

5. 
```
 const countries: Country[] = response.data.map((country) => ({
      name: {
        common: country.name.common,
      },
      capital: country.capital,
      flags: {
        svg: country.flags.svg,
      },
    }));
```
API 요청 하시는 부분이 상당히 인상 깊었습니다. 필요한 데이터만 받기 위해서 이렇게 하신걸까요 ?

**Comment by Dayeon-Cheon** [comment]
민곤님 바쁘신 와중에 피드백 주셔서 정말 감사합니다.

3. 말씀해 주신 대로 배열이 길어지면 연산 과정이 느려질 수 있다는 점을 고려해 더 효율적인 방법을 고민해 보고 싶습니다.
4. 네이밍 제안 감사합니다. "Card"를 다른 이름으로 수정하겠습니다.
5. 넵 필요한 부분만 매핑하여 사용했습니다.

덕분에 코드를 더욱 개선할 수 있을 것 같습니다. 다시 한번 감사드립니다. 🙇
